In [1]:
import tensorflow as tf
import keras
from keras import layers
import cv2

In [2]:
# pip install opencv-python

In [3]:
img=cv2.imread("cat.jpeg",cv2.IMREAD_GRAYSCALE)
img=cv2.resize(img,(224,224))
height,width=img.shape

In [16]:
model=keras.Sequential()
model.add(layers.Conv2D(input_shape=(height,width,1),filters=64,kernel_size=(7,7)))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_1 (Conv2D)           (None, 218, 218, 64)      3200      
                                                                 
Total params: 3,200
Trainable params: 3,200
Non-trainable params: 0
_________________________________________________________________


In [17]:
filters,_=model.layers[0].get_weights()
print(filters.shape)

(7, 7, 1, 64)


In [18]:
f=filters[:,:,:,0]
print(f)

[[[-0.01841129]
  [ 0.00408986]
  [-0.0210937 ]
  [ 0.00059787]
  [-0.00364966]
  [-0.00899341]
  [ 0.02415107]]

 [[ 0.01053375]
  [ 0.0124043 ]
  [ 0.04006072]
  [-0.01886708]
  [ 0.0315907 ]
  [ 0.01494527]
  [ 0.03415504]]

 [[ 0.01709887]
  [-0.03188841]
  [-0.01180242]
  [ 0.02078046]
  [-0.02887964]
  [-0.01113477]
  [ 0.03227403]]

 [[ 0.01173456]
  [-0.03608022]
  [-0.00114511]
  [ 0.03727134]
  [ 0.00837224]
  [ 0.01185184]
  [ 0.00966233]]

 [[ 0.00074083]
  [-0.01515905]
  [ 0.01036003]
  [ 0.00691317]
  [-0.02810558]
  [-0.04140459]
  [ 0.03765878]]

 [[ 0.03665243]
  [-0.02080479]
  [-0.00390361]
  [ 0.04214494]
  [ 0.02570805]
  [-0.01067909]
  [-0.01554079]]

 [[ 0.00978115]
  [ 0.00799114]
  [-0.02381235]
  [-0.02592222]
  [ 0.03414332]
  [ 0.03783889]
  [-0.03975351]]]


In [13]:
f_min, f_max=filters.min(), filters.max()
print(f_min,f_max)
filters=(filters-f_min)/(f_max-f_min)

-0.10115449 0.10126725


In [19]:
cv2.resize(f,(250,250),interpolation=cv2.INTER_NEAREST)
cv2.imshow("Filters",f)
cv2.waitKey(0)

KeyboardInterrupt: 

In [ ]:
for i in range(3):
    f=filters[:,:,:,i]
    print(f)
    cv2.resize(f,(250,250),interpolation=cv2.INTER_NEAREST)
    cv2.imshow("Filters",f)
cv2.waitKey(0)
    

In [32]:
import numpy as np
img1=model.predict(np.array(cv2.resize(img,(224,224)).reshape(1,224,224,1)))
print(img1)

cv2.imshow("predcited_img",img1)
cv2.waitKey(0)

1/1 [==============================] - 0s 10ms/step
[[[[ 1.83699856e+01 -1.63840771e+01  5.37293100e+00 ... -4.54036980e+01
    -2.79766197e+01  3.40359521e+00]
   [ 1.82660866e+01 -1.61882477e+01  5.77137709e+00 ... -4.49785385e+01
    -2.82008095e+01  3.40777588e+00]
   [ 1.75423908e+01 -1.54659252e+01  6.14135981e+00 ... -4.42506371e+01
    -2.81538353e+01  3.48461771e+00]
   ...
   [ 7.75230312e+00 -5.40357018e+00  2.91930842e+00 ... -1.59327431e+01
    -1.22436857e+01  1.85547471e-01]
   [ 7.22333574e+00 -5.52292585e+00  2.88066673e+00 ... -1.58193645e+01
    -1.22572851e+01 -2.86359310e-01]
   [ 7.04538298e+00 -6.88700390e+00  2.49783707e+00 ... -1.60901375e+01
    -1.18347349e+01 -1.62525520e-01]]

  [[ 1.83249073e+01 -1.54378519e+01  2.24031162e+00 ... -4.32594376e+01
    -2.74192772e+01  1.73621750e+00]
   [ 1.83744087e+01 -1.58255186e+01  3.42850757e+00 ... -4.36018982e+01
    -2.73205376e+01  2.28357005e+00]
   [ 1.80061073e+01 -1.59938383e+01  3.90721154e+00 ... -4.40920944

error: OpenCV(4.7.0) /Users/xperience/GHA-OCV-Python/_work/opencv-python/opencv-python/opencv/modules/core/src/matrix_c.cpp:190: error: (-5:Bad argument) Unknown array type in function 'cvarrToMat'
